(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const chapter=page==='index.html'||page===''?'ch0':page==='chapter1.html'?'ch1':page==='chapter2.html'?'ch2':page==='chapter3.html'?'ch3':page==='chapter4.html'?'ch4':page==='chapter5.html'?'ch5':page==='chapter6.html'?'ch6':null;
if(!chapter)return;
const DATA={
  ch0:{title:'第 0 章 · 创世',scope:'CAIE 9618 (2026) §1.1 DATA REPRESENTATION · SUBSET / PARTIAL',outcomes:['继续一个小型非负 binary pattern','把 denary digits 分别表示为 BCD','比较 ASCII 与 Unicode 的字符表示能力'],syllabusGaps:'prefixes · hexadecimal · one’s/two’s complement · binary arithmetic · overflow · extended ASCII',outOfScope:'PIXEL / COLOUR 在本章只是 §1.2 preview，不生成正式 graphics evidence。',model:'世界点亮、道路与祭坛是叙事教学模型；PIXEL / COLOUR 在本章只作 §1.2 preview。',phases:{TEACH:['title','wake','binary'],GUIDED_PRACTICE:['binary','clock','ascii','uni'],APPLY:['pixel','colour'],CHECKPOINT:['altar','ending','end']}},
  ch1:{title:'第 1 章 · 颜色的重量',scope:'CAIE 9618 (2026) §1.2 GRAPHICS · BITMAP',outcomes:['解释 pixel grid、binary colour codes 与 file header 如何表示 bitmap','区分 image resolution、screen resolution 与 colour depth','按 supplied fixture 估算未压缩 bitmap 大小，并说明 resolution / depth 对质量与大小的影响'],syllabusGaps:'Vector + suitability · Sound · Compression',outOfScope:'RLE、lossless / lossy 与其他 compression 内容全部留到 CH.04；旧 mixed-scope 存档不生成 Bitmap evidence。',model:'尺寸、bit depth、header、palette 与 byte totals 都是题目提供的教学 fixture，不是真实格式的固定值。',phases:{COURSE_CARD:['course_card'],TEACH:['teach_header','teach_pixels','teach_grids'],GUIDED_PRACTICE:['guided_g1_rebuild','guided_g2_terms'],APPLY:['apply_a1_size','apply_a2_tradeoffs'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4'],EVIDENCE:['commit_evidence','evidence','evidence_retry']}},
  ch2:{title:'第 3 章 · 第一声',scope:'CAIE 9618 (2026) §1.2 MULTIMEDIA · SOUND',outcomes:['解释 analogue continuous wave 如何经 sampling 形成 digital binary samples','区分 sampling rate 与 sampling resolution','说明两者对 accuracy 与 file size 的影响'],syllabusGaps:'sound-file compression (§1.3)',outOfScope:'本章只考 Sound 表示与 sampling；下一章再学习 Compression。现实音质阈值不在本章计分范围。',model:'4/8/16 samples/s 与 2/4/8 bits 只是 supplied controlled-comparison examples；每次比较保持其他因素不变。',phases:{TEACH:['teach_encoding','teach_rate','teach_resolution'],GUIDED_PRACTICE:['guided_g1_chain','guided_g2_effects'],APPLY:['apply_a1_compare','apply_a2_combined'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4']}},
  ch3:{title:'第 2 章 · 没有碎掉的门',scope:'CAIE 9618 (2026) §1.2 GRAPHICS · VECTOR + SUITABILITY',outcomes:['识别 drawing object、property 与 drawing list','比较 copied pixels 与 redrawn vector objects','根据用途选择 bitmap 或 vector 并说明理由'],syllabusGaps:'Sound · compression',outOfScope:'specific vector formats 与 vector compression 不是本章目标；vector 不等于“总是更小”。',model:'GEOMETRY INTEGRITY 与铸造室是教学模型；vector 不等于“总是更小”。',phases:{TEACH:['teach_encoding','teach_properties'],GUIDED_PRACTICE:['guided_g1_objects','guided_g2_list'],APPLY:['apply_a1_scale','apply_a2_suitability'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4']}},
  ch4:{title:'第 4 章 · 可以忘记多少',scope:'CAIE 9618 (2026) §1.3 COMPRESSION · STRICT V2',outcomes:['说明 compression 的需要、例子与用途，并区分 lossless / lossy','按情境说明选择理由，并解释 text / bitmap / vector / sound 如何压缩','用 (count, value) 完成短 RLE 编码/解码，并判断适用性'],syllabusGaps:'下一章：§2.1 Networks including the internet',outOfScope:'RLE 是本节唯一点名算法；Huffman、LZW、DEFLATE、JPEG/DCT、MP3、codec internals、网络协议、压缩率公式和现实质量阈值均不作为本章必学或计分内容。',model:'61/64、quality 88 与非 RLE 方法均为 COURSE EXAMPLE / 非考纲点名算法；正式证据只来自独立 P1–P5。',phases:{COURSE_CARD:['course_card','arrival','title'],TEACH:['teach_need','teach_modes','teach_rle'],GUIDED_PRACTICE:['guided_g1_restore','guided_g2_files','guided_g3_rle'],APPLY:['apply_a1_situations','apply_a2_fixture'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4','checkpoint_p5','commit_evidence'],EVIDENCE:['evidence','evidence_retry','end']}},
  ch5:{title:'第 5 章 · 网络如何连接',scope:'CAIE 9618 (2026) §2.1 NETWORKS INCLUDING THE INTERNET · N1 NETWORK FOUNDATIONS / PARTIAL',outcomes:['说明设备联网的目的与益处，并依据覆盖范围和网络关系区分 LAN / WAN','解释 client-server、peer-to-peer、thin client 与 thick client 的角色、优缺点和适用情境','识别 bus、star、mesh、hybrid topology，沿已有连接说明 host-to-host packet path，并论证情境选择'],syllabusGaps:'N2 Cloud & Transmission Media · 后续 LAN infrastructure / Ethernet · streaming / internet infrastructure · addressing / name resolution；§2.1 仍为 PARTIAL。',outOfScope:'本章不教授 packet 内部结构、确认或重传行为、网络协议、寻址、网络硬件细节或后续传输介质；这些内容不进入 P1–P5 facts。',model:'大厅中的节点、连接线与中性 packet 标记只是给定 topology 的可视化教学模型；正式证据只来自独立 P1–P5，并且只解锁 N2。',phases:{COURSE_CARD:['course_card','arrival','title'],TEACH:['teach_purpose','teach_lan_wan','teach_models','teach_clients','teach_topologies'],GUIDED_PRACTICE:['guided_g1_scope','guided_g2_models','guided_g3_clients','guided_g4_topologies'],APPLY:['apply_a1_models','apply_a2_topologies','apply_a3_terms'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4','checkpoint_p5','commit_evidence'],EVIDENCE:['evidence','evidence_retry','end']}},
  ch6:{title:'第 6 章 · 云端与介质',scope:'CAIE 9618 (2026) §2.1 NETWORKS INCLUDING THE INTERNET · N2 CLOUD & TRANSMISSION MEDIA / PARTIAL',outcomes:['解释 cloud computing 的使用，并区分 public cloud 与 private cloud','依据给定情境权衡 cloud computing 的 benefit 与 drawback，以及 wired / wireless 的差异和 implications','描述 copper、fibre-optic、radio waves（including WiFi）、microwaves 与 satellites 的相对特征'],syllabusGaps:'SUCCESSOR · N3 LAN INFRASTRUCTURE；后续 router / Ethernet / CSMA-CD · streaming / internet infrastructure · addressing / name resolution；§2.1 仍为 PARTIAL。',outOfScope:'本章不教授 LAN hardware、router、Ethernet/CSMA-CD、streaming、internet infrastructure、IP/DNS、协议机制、云服务层级或现实固定速率/距离阈值；public/private cloud 不等于 public/private IP。',model:'云台、传输舱与链路效果只是比较可观察特征的教学模型；正式证据只来自独立 P1–P5，并且只解锁 N3 LAN INFRASTRUCTURE。',phases:{COURSE_CARD:['course_card'],TEACH:['teach_cloud','teach_types','teach_tradeoffs','teach_modes','teach_media'],GUIDED_PRACTICE:['guided_g1_clouds','guided_g2_tradeoffs','guided_g3_modes','guided_g4_media'],APPLY:['apply_a1_cloud','apply_a2_modes','apply_a3_media','apply_a4_family'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4','checkpoint_p5','commit_evidence'],EVIDENCE:['evidence','evidence_retry']}}
};
const d=DATA[chapter];
function stage(){try{if(chapter==='ch0'&&typeof G!=='undefined')return String(G.beat||'title');if(typeof S!=='undefined')return String(S.stage||'arrival')}catch(e){}return chapter==='ch0'?'title':'arrival'}
function phase(){const s=stage().toLowerCase();const order=['COURSE_CARD','TEACH','GUIDED_PRACTICE','APPLY','CHECKPOINT','EVIDENCE'];for(const p of order)if((d.phases[p]||[]).includes(s))return p;if(s.startsWith('course'))return'COURSE_CARD';if(s.startsWith('teach'))return'TEACH';if(s.startsWith('guided'))return'GUIDED_PRACTICE';if(s.startsWith('apply'))return'APPLY';if(s.startsWith('checkpoint'))return'CHECKPOINT';if(s.startsWith('evidence')||s==='end')return'EVIDENCE';return chapter==='ch4'||chapter==='ch5'||chapter==='ch6'?'COURSE_CARD':'TEACH'}
function phaseLabels(){return['COURSE_CARD','TEACH','GUIDED_PRACTICE','APPLY','CHECKPOINT','EVIDENCE'].filter(p=>Object.prototype.hasOwnProperty.call(d.phases,p))}
const style=document.createElement('style');
style.textContent=`#courseGuideButton{position:fixed;z-index:9000;right:18px;top:58px;min-width:118px;min-height:44px;padding:8px 11px;border:1px solid #4bbf92;background:#03120ee8;color:#cffff0;font:12px Consolas,"Microsoft YaHei",monospace;cursor:pointer;box-shadow:0 0 18px #052d23}#courseGuideButton:hover,#courseGuideButton:focus{background:#0b3025;outline:2px solid #92ffd1;outline-offset:2px}#courseGuideOverlay{position:fixed;z-index:10000;inset:0;display:none;place-items:center;padding:18px;background:#000c}#courseGuideOverlay.open{display:grid}.cg-card{width:min(720px,96vw);max-height:90vh;overflow:auto;border:1px solid #4bbf92;background:#03100ded;color:#d8ffeb;padding:22px;box-shadow:0 0 42px #0c3d2d;font:14px/1.6 Consolas,"Microsoft YaHei",monospace}.cg-card h2{margin:0 0 10px;color:#8effbd}.cg-scope,.cg-model,.cg-inline{border:1px solid #326e58;background:#051a14;padding:11px 13px;margin:12px 0}.cg-model{border-color:#8b7341;color:#f2d99a}.cg-phases{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:13px 0}.cg-phase{padding:7px 5px;border:1px solid #315d4e;color:#7ea998;text-align:center;font-size:10px}.cg-phase.on{border-color:#8effbd;background:#123b2d;color:#fff}.cg-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}.cg-btn{min-height:44px;padding:9px 13px;border:1px solid #4bbf92;background:#0a2b20;color:#e1fff0;font:inherit;cursor:pointer}.cg-btn.sub{border-color:#536b61;background:#0a1310;color:#b3c7bd}.cg-inline{font:12px/1.55 Consolas,"Microsoft YaHei",monospace;color:#d4ffe6}.cg-inline b{color:#8effbd}.cg-inline a{color:#9dffe0}.cg-card ul{padding-left:22px}.cg-card summary{cursor:pointer;color:#a9d9c6}@media(max-width:640px){#courseGuideButton{right:10px;top:auto;bottom:10px;min-width:108px}.cg-card{padding:16px}.cg-phases{grid-template-columns:1fr 1fr}.cg-inline{font-size:11px}}`;
document.head.appendChild(style);
const button=document.createElement('button');button.id='courseGuideButton';button.type='button';button.textContent='COURSE · GUIDE';button.setAttribute('aria-haspopup','dialog');document.body.appendChild(button);
const overlay=document.createElement('div');overlay.id='courseGuideOverlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','courseGuideTitle');overlay.innerHTML='<section class="cg-card"><h2 id="courseGuideTitle"></h2><div class="cg-scope" id="courseGuideScope"></div><div class="cg-phases" id="courseGuidePhases"></div><p><b>CURRENT GOAL / 当前教学关：</b><span id="courseGuideCurrent"></span></p><p><b>YOU WILL / 本章目标</b></p><ul id="courseGuideOutcomes"></ul><div class="cg-model"><b>[TEACHING MODEL · 教学模型]</b><br><span id="courseGuideModel"></span></div><details><summary>SYLLABUS GAPS / 尚待学习的考纲知识</summary><p id="courseGuideGaps"></p></details><details><summary>OUT OF SCOPE / 非本章目标</summary><p id="courseGuideOut"></p></details><div class="cg-actions"><button class="cg-btn" id="courseGuideMap">COURSE MAP · 课程地图</button><button class="cg-btn sub" id="courseGuideClose">返回游戏</button></div></section>';
document.body.appendChild(overlay);
let lastFocus=null,savedScrollY=0,savedOverflow='',isolated=[];
function render(){document.getElementById('courseGuideTitle').textContent=d.title;document.getElementById('courseGuideScope').innerHTML='<b>OFFICIAL SCOPE</b><br>'+d.scope;document.getElementById('courseGuideCurrent').textContent=phase()+' · '+stage().toUpperCase();document.getElementById('courseGuideOutcomes').innerHTML=d.outcomes.map(x=>'<li>'+x+'</li>').join('');document.getElementById('courseGuideModel').textContent=d.model;document.getElementById('courseGuideGaps').textContent=d.syllabusGaps;document.getElementById('courseGuideOut').textContent=d.outOfScope;document.getElementById('courseGuidePhases').innerHTML=phaseLabels().map(x=>'<div class="cg-phase '+(x===phase()?'on':'')+'">'+x.replaceAll('_',' ')+'</div>').join('')}
function guideFocusables(){return Array.from(overlay.querySelectorAll('button,a[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')).filter(x=>!x.disabled&&!x.hidden)}
function openGuide(){lastFocus=document.activeElement;savedScrollY=scrollY;savedOverflow=document.body.style.overflow;render();isolated=Array.from(document.body.children).filter(x=>x!==overlay).map(node=>({node,inert:node.inert}));isolated.forEach(x=>x.node.inert=true);document.body.style.overflow='hidden';overlay.classList.add('open');button.setAttribute('aria-expanded','true');const card=overlay.querySelector('.cg-card');if(card)card.scrollTop=0;document.getElementById('courseGuideClose').focus()}
function closeGuide(){overlay.classList.remove('open');button.setAttribute('aria-expanded','false');isolated.forEach(x=>x.node.inert=x.inert);isolated=[];document.body.style.overflow=savedOverflow;scrollTo(0,savedScrollY);if(lastFocus&&lastFocus.focus)lastFocus.focus()}
button.addEventListener('click',openGuide);document.getElementById('courseGuideClose').addEventListener('click',closeGuide);document.getElementById('courseGuideMap').addEventListener('click',()=>location.href='course-map.html');overlay.addEventListener('click',e=>{if(e.target===overlay)closeGuide()});
addEventListener('keydown',e=>{if(e.key==='Tab'&&overlay.classList.contains('open')){const list=guideFocusables();if(!list.length){e.preventDefault();return}const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}return}if((e.key==='g'||e.key==='G')&&!e.ctrlKey&&!e.metaKey&&!e.altKey){const tag=(document.activeElement&&document.activeElement.tagName)||'';if(!['INPUT','TEXTAREA','SELECT'].includes(tag)){e.preventDefault();overlay.classList.contains('open')?closeGuide():openGuide()}}else if(e.key==='Escape'&&overlay.classList.contains('open')){e.preventDefault();e.stopImmediatePropagation();closeGuide()}},true);
function injectCourseCard(){const p=document.getElementById('panel');if(!p||p.querySelector('.cg-inline'))return;const s=stage();if(!['arrival','title','course_card'].includes(s))return;const h=p.querySelector('h1,h2');if(!h)return;const route=phaseLabels().map(x=>x.replaceAll('_',' ')+((chapter==='ch4'||chapter==='ch5'||chapter==='ch6')&&x==='CHECKPOINT'?' P1–P5':'')).join(' → '),card=document.createElement('div');card.className='cg-inline';card.innerHTML='<b>'+d.scope+'</b><br>教学路线：'+route+'<br><a href="course-map.html">查看完整课程地图与尚未覆盖内容</a>';h.insertAdjacentElement('afterend',card)}
injectCourseCard();const panel=document.getElementById('panel');if(panel)new MutationObserver(injectCourseCard).observe(panel,{childList:true});
if(new URLSearchParams(location.search).has('guide'))setTimeout(openGuide,80);
})();
