(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const chapter=page==='index.html'||page===''?'ch0':page==='chapter1.html'?'ch1':page==='chapter2.html'?'ch2':page==='chapter3.html'?'ch3':null;
if(!chapter)return;
const DATA={
  ch0:{title:'第 0 章 · 创世',scope:'CAIE 9618 (2026) §1.1 DATA REPRESENTATION · SUBSET / PARTIAL',outcomes:['继续一个小型非负 binary pattern','把 denary digits 分别表示为 BCD','比较 ASCII 与 Unicode 的字符表示能力'],syllabusGaps:'prefixes · hexadecimal · one’s/two’s complement · binary arithmetic · overflow · extended ASCII',outOfScope:'PIXEL / COLOUR 在本章只是 §1.2 preview，不生成正式 graphics evidence。',model:'世界点亮、道路与祭坛是叙事教学模型；PIXEL / COLOUR 在本章只作 §1.2 preview。',phases:{TEACH:['title','wake','binary'],GUIDED_PRACTICE:['binary','clock','ascii','uni'],APPLY:['pixel','colour'],CHECKPOINT:['altar','ending','end']}},
  ch1:{title:'第 1 章 · 颜色的重量',scope:'CAIE 9618 (2026) §1.2 GRAPHICS · BITMAP SUBSET + §1.3 RLE SUBSET',outcomes:['用 colour depth 估算固定 resolution 的 pixel data','把连续相同 values 写成 RLE count + value','验证 lossless round-trip，并判断 RLE 何时会膨胀'],syllabusGaps:'file header · screen resolution · system comparison of image resolution',outOfScope:'完整 §1.3 Compression 在 Chapter 4 形成证据。',model:'64-byte buffer 与 storage units 是教学模型，不是真实文件格式限制。',phases:{TEACH:['arrival','weight'],GUIDED_PRACTICE:['scan'],APPLY:['contrast','mural'],CHECKPOINT:['end']}},
  ch2:{title:'第 3 章 · 第一声',scope:'CAIE 9618 (2026) §1.2 MULTIMEDIA · SOUND',outcomes:['把 analogue wave 表示为 digital samples','比较 sampling rate 与 sampling resolution','联系 accuracy 与 uncompressed file size'],syllabusGaps:'sound-file compression (§1.3)',outOfScope:'real codec thresholds are not required here and the game values are not real thresholds.',model:'4/8/16 Hz、bit choices 与 buffer limit 是教学模型，不代表现实声音质量门槛。',phases:{TEACH:['arrival','rate'],GUIDED_PRACTICE:['rate','resolution'],APPLY:['mix','awakening'],CHECKPOINT:['end']}},
  ch3:{title:'第 2 章 · 没有碎掉的门',scope:'CAIE 9618 (2026) §1.2 GRAPHICS · VECTOR + SUITABILITY',outcomes:['识别 drawing object、property 与 drawing list','比较 copied pixels 与 redrawn vector objects','根据用途选择 bitmap 或 vector 并说明理由'],syllabusGaps:'Sound · compression',outOfScope:'specific vector formats 与 vector compression 不是本章目标；vector 不等于“总是更小”。',model:'GEOMETRY INTEGRITY 与铸造室是教学模型；vector 不等于“总是更小”。',phases:{TEACH:['teach_encoding','teach_properties'],GUIDED_PRACTICE:['guided_g1_objects','guided_g2_list'],APPLY:['apply_a1_scale','apply_a2_suitability'],CHECKPOINT:['checkpoint_p1','checkpoint_p2','checkpoint_p3','checkpoint_p4']}}
};
const d=DATA[chapter];
function stage(){try{if(chapter==='ch0'&&typeof G!=='undefined')return String(G.beat||'title');if(typeof S!=='undefined')return String(S.stage||'arrival')}catch(e){}return chapter==='ch0'?'title':'arrival'}
function phase(){const s=stage();for(const p of ['TEACH','GUIDED_PRACTICE','APPLY','CHECKPOINT'])if((d.phases[p]||[]).includes(s))return p;return'TEACH'}
const style=document.createElement('style');
style.textContent=`#courseGuideButton{position:fixed;z-index:9000;right:18px;top:58px;min-width:118px;min-height:44px;padding:8px 11px;border:1px solid #4bbf92;background:#03120ee8;color:#cffff0;font:12px Consolas,"Microsoft YaHei",monospace;cursor:pointer;box-shadow:0 0 18px #052d23}#courseGuideButton:hover,#courseGuideButton:focus{background:#0b3025;outline:2px solid #92ffd1;outline-offset:2px}#courseGuideOverlay{position:fixed;z-index:10000;inset:0;display:none;place-items:center;padding:18px;background:#000c}#courseGuideOverlay.open{display:grid}.cg-card{width:min(720px,96vw);max-height:90vh;overflow:auto;border:1px solid #4bbf92;background:#03100ded;color:#d8ffeb;padding:22px;box-shadow:0 0 42px #0c3d2d;font:14px/1.6 Consolas,"Microsoft YaHei",monospace}.cg-card h2{margin:0 0 10px;color:#8effbd}.cg-scope,.cg-model,.cg-inline{border:1px solid #326e58;background:#051a14;padding:11px 13px;margin:12px 0}.cg-model{border-color:#8b7341;color:#f2d99a}.cg-phases{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:13px 0}.cg-phase{padding:7px 5px;border:1px solid #315d4e;color:#7ea998;text-align:center;font-size:10px}.cg-phase.on{border-color:#8effbd;background:#123b2d;color:#fff}.cg-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}.cg-btn{min-height:44px;padding:9px 13px;border:1px solid #4bbf92;background:#0a2b20;color:#e1fff0;font:inherit;cursor:pointer}.cg-btn.sub{border-color:#536b61;background:#0a1310;color:#b3c7bd}.cg-inline{font:12px/1.55 Consolas,"Microsoft YaHei",monospace;color:#d4ffe6}.cg-inline b{color:#8effbd}.cg-inline a{color:#9dffe0}.cg-card ul{padding-left:22px}.cg-card summary{cursor:pointer;color:#a9d9c6}@media(max-width:640px){#courseGuideButton{right:10px;top:auto;bottom:10px;min-width:108px}.cg-card{padding:16px}.cg-phases{grid-template-columns:1fr 1fr}.cg-inline{font-size:11px}}`;
document.head.appendChild(style);
const button=document.createElement('button');button.id='courseGuideButton';button.type='button';button.textContent='COURSE · GUIDE';button.setAttribute('aria-haspopup','dialog');document.body.appendChild(button);
const overlay=document.createElement('div');overlay.id='courseGuideOverlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','courseGuideTitle');overlay.innerHTML='<section class="cg-card"><h2 id="courseGuideTitle"></h2><div class="cg-scope" id="courseGuideScope"></div><div class="cg-phases" id="courseGuidePhases"></div><p><b>CURRENT GOAL / 当前教学关：</b><span id="courseGuideCurrent"></span></p><p><b>YOU WILL / 本章目标</b></p><ul id="courseGuideOutcomes"></ul><div class="cg-model"><b>[TEACHING MODEL · 教学模型]</b><br><span id="courseGuideModel"></span></div><details><summary>SYLLABUS GAPS / 尚待学习的考纲知识</summary><p id="courseGuideGaps"></p></details><details><summary>OUT OF SCOPE / 非本章目标</summary><p id="courseGuideOut"></p></details><div class="cg-actions"><button class="cg-btn" id="courseGuideMap">COURSE MAP · 课程地图</button><button class="cg-btn sub" id="courseGuideClose">返回游戏</button></div></section>';
document.body.appendChild(overlay);
let lastFocus=null;
function render(){document.getElementById('courseGuideTitle').textContent=d.title;document.getElementById('courseGuideScope').innerHTML='<b>OFFICIAL SCOPE</b><br>'+d.scope;document.getElementById('courseGuideCurrent').textContent=phase()+' · '+stage().toUpperCase();document.getElementById('courseGuideOutcomes').innerHTML=d.outcomes.map(x=>'<li>'+x+'</li>').join('');document.getElementById('courseGuideModel').textContent=d.model;document.getElementById('courseGuideGaps').textContent=d.syllabusGaps;document.getElementById('courseGuideOut').textContent=d.outOfScope;document.getElementById('courseGuidePhases').innerHTML=['TEACH','GUIDED PRACTICE','APPLY','CHECKPOINT'].map(x=>'<div class="cg-phase '+(x===phase()?'on':'')+'">'+x+'</div>').join('')}
function openGuide(){lastFocus=document.activeElement;render();overlay.classList.add('open');button.setAttribute('aria-expanded','true');document.getElementById('courseGuideClose').focus()}
function closeGuide(){overlay.classList.remove('open');button.setAttribute('aria-expanded','false');if(lastFocus&&lastFocus.focus)lastFocus.focus()}
button.addEventListener('click',openGuide);document.getElementById('courseGuideClose').addEventListener('click',closeGuide);document.getElementById('courseGuideMap').addEventListener('click',()=>location.href='course-map.html');overlay.addEventListener('click',e=>{if(e.target===overlay)closeGuide()});
addEventListener('keydown',e=>{if((e.key==='g'||e.key==='G')&&!e.ctrlKey&&!e.metaKey&&!e.altKey){const tag=(document.activeElement&&document.activeElement.tagName)||'';if(!['INPUT','TEXTAREA','SELECT'].includes(tag)){e.preventDefault();overlay.classList.contains('open')?closeGuide():openGuide()}}else if(e.key==='Escape'&&overlay.classList.contains('open')){e.preventDefault();e.stopImmediatePropagation();closeGuide()}},true);
function injectCourseCard(){const p=document.getElementById('panel');if(!p||p.querySelector('.cg-inline'))return;const s=stage();if(!['arrival','title'].includes(s))return;const h=p.querySelector('h1,h2');if(!h)return;const card=document.createElement('div');card.className='cg-inline';card.innerHTML='<b>'+d.scope+'</b><br>教学路线：TEACH → GUIDED PRACTICE → APPLY → CHECKPOINT<br><a href="course-map.html">查看完整课程地图与尚未覆盖内容</a>';h.insertAdjacentElement('afterend',card)}
injectCourseCard();const panel=document.getElementById('panel');if(panel)new MutationObserver(injectCourseCard).observe(panel,{childList:true});
if(new URLSearchParams(location.search).has('guide'))setTimeout(openGuide,80);
})();
